export const designs = [
  {
    id: 1,
    slug: 'onyx-prestige',
    name: 'Onyx Prestige',
    tagline: 'Minimalist black tailoring with warm gold trim',
    collar: 'mandarin',
    pocket: 'besom',
    cargo: false,
    logo: true,
    colors: { primary: '#1C1C1E', accent: '#3F3F44', piping: '#B7A369', line: '#000000' },
    palette: [
      { name: 'Onyx Black', hex: '#1C1C1E' },
      { name: 'Graphite Panel', hex: '#3F3F44' },
      { name: 'Warm Gold Trim', hex: '#B7A369' },
      { name: 'Ivory Lining', hex: '#F4F1EA' },
    ],
    notes: [
      'Body: 4-way stretch poplin, 78% polyester / 18% rayon / 4% spandex, matte finish',
      'Mandarin collar stand with concealed gold-tone piping insert',
      'Hidden besom (welt) chest pocket — no visible pocket bag for a clean minimal front',
      'Princess seams both sides, front and back, for a tailored silhouette',
      'Interior utility loop at left hip; side-seam hand pockets on pants',
      'Gold-tone "S" monogram embroidered above left chest, 25mm',
      'Straight-leg pant, covered elastic + interior drawcord waistband',
    ],
  },
  {
    id: 2,
    slug: 'sage-serenity',
    name: 'Sage Serenity',
    tagline: 'Soft sage with warm ivory contrast panels',
    collar: 'mandarin',
    pocket: 'patch',
    cargo: false,
    logo: true,
    colors: { primary: '#8A9A82', accent: '#F1EDE4', piping: '#5C6B54', line: '#3D4438' },
    palette: [
      { name: 'Sage Green', hex: '#8A9A82' },
      { name: 'Warm Ivory Contrast', hex: '#F1EDE4' },
      { name: 'Deep Sage Trim', hex: '#5C6B54' },
      { name: 'Bark Stitching', hex: '#3D4438' },
    ],
    notes: [
      'Body: brushed peached twill, 92% polyester / 8% spandex, soft-hand antimicrobial finish',
      'Mandarin collar in deep sage with ivory-piped edge',
      'Ivory contrast patch pocket, left chest, topstitched in deep sage',
      'Curved yoke seam at back with matching princess seams front/back',
      'Ivory contrast waistband on pant, internal drawcord + soft elastic back',
      'Deep-sage tonal monogram above pocket, 25mm',
      'Side-seam pockets + single back pocket on pant',
    ],
  },
  {
    id: 3,
    slug: 'rose-quartz',
    name: 'Rose Quartz',
    tagline: 'Dusty blush with mauve tailoring details',
    collar: 'v',
    pocket: 'patch',
    cargo: false,
    logo: true,
    colors: { primary: '#E3C4C0', accent: '#8E6C6C', piping: '#8E6C6C', line: '#5A4646' },
    palette: [
      { name: 'Dusty Blush', hex: '#E3C4C0' },
      { name: 'Mauve Panel', hex: '#8E6C6C' },
      { name: 'Mauve Trim', hex: '#8E6C6C' },
      { name: 'Espresso Stitching', hex: '#5A4646' },
    ],
    notes: [
      'Body: liquid-cotton jersey-woven blend, 95% polyester / 5% spandex, 4-way stretch',
      'Soft V-neckline with self-fabric facing, mauve edge binding',
      'Mauve contrast patch pocket, left chest, rounded corner',
      'Front princess seams for a fitted-but-relaxed silhouette',
      'Jogger-style pant: mauve ribbed cuff at ankle, drawcord waistband',
      'Mauve tonal monogram above pocket, 25mm',
      'Side-seam pockets on pant, back yoke seam on top',
    ],
  },
  {
    id: 4,
    slug: 'midnight-aviator',
    name: 'Midnight Aviator',
    tagline: 'Navy tailoring with steel-blue piping and cargo utility',
    collar: 'mandarin',
    pocket: 'patch',
    cargo: true,
    logo: true,
    colors: { primary: '#1B2A41', accent: '#4E6E8E', piping: '#C7CDD1', line: '#0E1620' },
    palette: [
      { name: 'Midnight Navy', hex: '#1B2A41' },
      { name: 'Steel Blue Panel', hex: '#4E6E8E' },
      { name: 'Silver Piping', hex: '#C7CDD1' },
      { name: 'Ink Stitching', hex: '#0E1620' },
    ],
    notes: [
      'Body: performance stretch twill, 88% polyester / 12% spandex, water-repellent finish',
      'Mandarin collar with silver piping insert along the stand',
      'Steel-blue contrast patch pocket, left chest, silver topstitch',
      'Utility cargo pocket, right thigh, snap-flap closure',
      'Reinforced princess seams and back yoke for athletic movement',
      'Silver tonal monogram above pocket, 25mm',
      'Steel-blue contrast waistband, internal drawcord, tapered leg to ankle cuff',
    ],
  },
  {
    id: 5,
    slug: 'ivory-prestige',
    name: 'Ivory Prestige',
    tagline: 'Warm ivory with taupe-gold luxury minimalism',
    collar: 'v',
    pocket: 'patch',
    cargo: false,
    logo: true,
    colors: { primary: '#F3EFE7', accent: '#B79C7C', piping: '#B79C7C', line: '#6B5B4A' },
    palette: [
      { name: 'Warm Ivory', hex: '#F3EFE7' },
      { name: 'Taupe Gold Panel', hex: '#B79C7C' },
      { name: 'Taupe Gold Trim', hex: '#B79C7C' },
      { name: 'Deep Taupe Stitching', hex: '#6B5B4A' },
    ],
    notes: [
      'Body: matte sateen stretch weave, 80% polyester / 16% rayon / 4% spandex',
      'Soft V-neckline with taupe-gold self-binding',
      'Taupe-gold contrast patch pocket, left chest, clean edge topstitch',
      'Front princess seams, back yoke seam for a refined tailored line',
      'Taupe-gold contrast waistband, internal drawcord + back elastic',
      'Deep-taupe tonal monogram above pocket, 25mm',
      'Side-seam pockets on pant, straight leg with clean hem',
    ],
  },
];
